cc_binary(
    name = "log_aggregator",
    srcs = [
        "main.cpp",
        "LogEntry.cpp",
        "LogReader.cpp",
        "MetricStore.cpp",
        "ThreadPool.cpp",
        "ReportWriter.cpp",
    ],
    hdrs = [
        "LogEntry.hpp",
        "LogReader.hpp",
        "MetricStore.hpp",
        "ThreadPool.hpp",
        "ReportWriter.hpp",
    ],
    copts = ["-Wall", "-Wextra", "-std=c++17"],
)